export { default as Auth } from './Auth'
export { default as Admin } from './Admin'
export { default as Dentist } from './Dentist'
export { default as Patient } from './Patient'
export { default as Payment } from './Payment'