export { default as HelpSVG } from './HelpSVG'
export { default as FacebookSVG } from './FacebookSVG'
export { default as GoogleSVG } from './GoogleSVG'
export { default as SuccessSVG } from './SuccessSVG'
export { default as WarningSVG } from './WarningSVG'